"""init session tabs

Revision ID: 715c40ff5e28
Revises: 1b93bf7fe8b2
Create Date: 2025-04-22 23:16:03.996359

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "715c40ff5e28"
down_revision: Union[str, None] = "1b93bf7fe8b2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_sessions",
        sa.Column(
            "session_id",
            sa.UUID(),
            nullable=False,
            comment="Уникальный идентификатор сессии",
        ),
        sa.Column(
            "user_id",
            sa.UUID(),
            nullable=False,
            comment="Уникальный идентификатор пользователя",
        ),
        sa.Column(
            "user_agent",
            sa.String(length=255),
            nullable=True,
            comment="Клиентское устройство пользователя",
        ),
        sa.Column(
            "refresh_token",
            sa.String(),
            nullable=False,
            comment="Рефреш токен пользовательской сессии (JWT)",
        ),
        sa.Column("expires_at", sa.DateTime(), nullable=False, comment="Дата истечения сессии"),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("session_id"),
        schema="session",
    )
    op.create_table(
        "user_sessions_hist",
        sa.Column(
            "session_id",
            sa.UUID(),
            nullable=False,
            comment="Уникальный идентификатор сессии",
        ),
        sa.Column(
            "user_id",
            sa.UUID(),
            nullable=False,
            comment="Уникальный идентификатор пользователя",
        ),
        sa.Column(
            "user_agent",
            sa.String(length=255),
            nullable=True,
            comment="Клиентское устройство пользователя",
        ),
        sa.Column("expires_at", sa.DateTime(), nullable=False, comment="Дата истечения сессии"),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column(
            "user_device_type",
            sa.String(),
            nullable=False,
            server_default="WEB",
            comment="Тип устройства пользователя",
        ),
        sa.PrimaryKeyConstraint("session_id", "user_device_type"),
        postgresql_partition_by="LIST (user_device_type)",
        schema="session",
    )
    # Создание партиций
    op.execute(
        """
        CREATE TABLE IF NOT EXISTS session.users_sign_in_web
        PARTITION OF session.user_sessions_hist
        FOR VALUES IN ('WEB');
        """
    )
    op.execute(
        """
        CREATE TABLE IF NOT EXISTS session.users_sign_in_mobile
        PARTITION OF session.user_sessions_hist
        FOR VALUES IN ('PHONE');
        """
    )
    op.execute(
        """
        CREATE TABLE IF NOT EXISTS session.users_sign_in_smart
        PARTITION OF session.user_sessions_hist
        FOR VALUES IN ('TV');
        """
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # Удаление партиций
    op.execute("DROP TABLE IF EXISTS session.users_sign_in_web")
    op.execute("DROP TABLE IF EXISTS session.users_sign_in_mobile")
    op.execute("DROP TABLE IF EXISTS session.users_sign_in_smart")
    
    # Удаление основной таблицы
    op.drop_table("user_sessions_hist", schema="session")
    op.drop_table("user_sessions", schema="session")
