"""check

Revision ID: c30fd4a67156
Revises: 715c40ff5e28
Create Date: 2025-05-12 00:57:22.102030

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c30fd4a67156"
down_revision: Union[str, None] = "715c40ff5e28"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user", sa.Column("menter", sa.String(length=50), nullable=True), schema="profile"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "menter", schema="profile")
    # ### end Alembic commands ###
