"""add profile settings table

Revision ID: dfc5e1f60393
Revises: 68abe7b09fbe
Create Date: 2025-06-30 21:11:26.745652

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "dfc5e1f60393"
down_revision: Union[str, None] = "68abe7b09fbe"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_mail_confirmation",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("mail_verify_token", sa.String(length=255), nullable=True),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["profile.user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id"),
        schema="profile",
    )
    op.create_table(
        "user_profile_settings",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("user_timezone", sa.String(length=50), nullable=False),
        sa.Column(
            "is_email_notify_allowed",
            sa.Boolean(),
            server_default=sa.text("'true'"),
            nullable=False,
            comment="Разрешить отправку уведомлений на почту да/нет",
        ),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["profile.user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id"),
        schema="profile",
    )
    op.add_column(
        "user_cred",
        sa.Column(
            "is_verified_email",
            sa.Boolean(),
            server_default=sa.text("'false'"),
            nullable=False,
            comment="Подтвеждение email",
        ),
        schema="profile",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user_cred", "is_verified_email", schema="profile")
    op.drop_table("user_profile_settings", schema="profile")
    op.drop_table("user_mail_confirmation", schema="profile")
    # ### end Alembic commands ###
