repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-added-large-files
        exclude: ^docs/.*$
      - id: check-json
        exclude: ^(backup/elastic_dump/dump/.*\.json|docs/.*)$
      - id: debug-statements

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.9
    hooks:
      - id: ruff
        name: ruff-lint
        args: ["--fix", "--select=ALL", "--ignore=E203,W503,COM812,COM813,COM816"]
        exclude: ^(\.git/.*|\.github/.*|infra/.*|\.venv/.*|build/.*|dist/.*|docs/.*|.*/migrations/.*|.*/migration/.*|services/auth-service/src/migration/.*|backup/.*|.*__init__\.py)$
      - id: ruff-format
        name: ruff-format
        exclude: ^(\.git/.*|\.github/.*|infra/.*|\.venv/.*|build/.*|dist/.*|docs/.*|.*/migrations/.*|.*/migration/.*|services/auth-service/src/migration/.*|backup/.*|.*__init__\.py)$

  - repo: https://github.com/wemake-services/wemake-python-styleguide
    rev: 1.1.0
    hooks:
      - id: wemake-python-styleguide
        name: wemake-python-styleguide
        entry: flake8
        language: python
        language_version: python3.12
        additional_dependencies:
          - flake8==7.2.0
          - flake8-bandit==4.1.1
          - flake8-bugbear==23.7.10
          - flake8-broken-line==1.0.0
          - flake8-isort==6.1.1
          - flake8-logging-format==0.9.0
          - flake8-annotations==3.1.1
          - darglint==1.8.1
          - astor==0.8.1
          - attrs==25.3.0
          - setuptools<81.0.0
        args:
          - "--max-line-length=100"
          - "--extend-ignore=E203,W503,C812,C813,C814,C815,C816,WPS300,WPS111"
          - "--select=WPS"
        exclude: ^(\.git/.*|\.github/.*|infra/.*|\.venv/.*|build/.*|dist/.*|docs/.*|.*/migrations/.*|.*/migration/.*|services/auth-service/src/migration/.*|backup/.*|.*__init__\.py)$
