services:
  elasticsearch:
    image: elasticsearch:8.16.5
    container_name: elasticsearch-container
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    environment:
      - "discovery.type=single-node"
      - "xpack.security.enabled=false"
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    cpus: "2"         # Прямое ограничение CPU
    mem_limit: 1024M   # Прямое ограничение памяти
    command: bin/elasticsearch
    expose:
      - ${ELASTIC_PORT}
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9200"]
      interval: 10s
      timeout: 5s
      retries: 5

  kibana:
    image: kibana:8.16.5
    container_name: kibana-container
    environment:
      - ELASTICSEARCH_HOSTS="http://${ELASTIC_HOST}:${ELASTIC_PORT}"
      - ELASTICSEARCH_SECURITY_ENABLED=false
    cpus: "2"         # Прямое ограничение CPU
    mem_limit: 1024M   # Прямое ограничение памяти
    depends_on:
      elasticsearch:
        condition: service_healthy
    ports:
      - "${KIBANA_PORT}:${KIBANA_PORT}"
    restart: always

  es-init:
    container_name: es-init-container
    build:
      context: .
      dockerfile: backup/elastic_dump/dump_loader/Dockerfile
    depends_on:
      elasticsearch:
        condition: service_healthy
    environment:
      - ELASTIC_HOST=${ELASTIC_HOST}
      - ELASTIC_PORT=${ELASTIC_PORT}
    restart: "no"

  redis:
    image: redis:7-alpine
    container_name: redis-container
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_USER=${REDIS_USER}
      - REDIS_USER_PASSWORD=${REDIS_USER_PASSWORD}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_DB=${REDIS_DB}
    volumes:
      - redis_data:/data
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M
    command: >
      sh -c '
        mkdir -p /usr/local/etc/redis &&
        echo "bind 0.0.0.0" > /usr/local/etc/redis/redis.conf &&
        echo "requirepass $REDIS_PASSWORD" >> /usr/local/etc/redis/redis.conf &&
        echo "appendonly yes" >> /usr/local/etc/redis/redis.conf &&
        echo "appendfsync everysec" >> /usr/local/etc/redis/redis.conf &&
        echo "user default off" > /usr/local/etc/redis/users.acl &&
        echo "user $REDIS_USER on >$REDIS_USER_PASSWORD ~* +@all" >> /usr/local/etc/redis/users.acl &&
        redis-server /usr/local/etc/redis/redis.conf --aclfile /usr/local/etc/redis/users.acl
      '
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "$REDIS_PASSWORD", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: always

  auth-api:
    build:
      context: .
      dockerfile: ./services/auth-service/src/Dockerfile
    env_file:
      - ./.env
    cpus: "1"
    mem_limit: 256M
    depends_on:
      redis:
        condition: service_healthy
      postgres:
        condition: service_healthy
    restart: always
    healthcheck:
      test: [
        "CMD-SHELL",
        "PGPASSWORD=${POSTGRES_PASSWORD} psql -h postgres -U ${POSTGRES_USER} -d ${POSTGRES_DB} -t -c \"SELECT COUNT(*) FROM information_schema.tables WHERE table_schema = 'profile';\" | xargs -I {} test {} -ge 4"
      ]
      interval: 20s
      timeout: 10s
      retries: 10
      start_period: 30s

  async-api:
    build:
      context: .
      dockerfile: ./services/async-api/src/Dockerfile
    env_file:
      - ./.env
    cpus: "1"
    mem_limit: 256M
    depends_on:
      elasticsearch:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: always

  admin-panel:
    build:
      context: .
      dockerfile: ./services/admin-panel/src/Dockerfile
    env_file:
      - ./.env
    volumes:
      - static_django:/var/www/static
    depends_on:
      redis:
        condition: service_healthy
      postgres:
        condition: service_healthy
      auth-api:
        condition: service_healthy


  postgres:
    image: postgres:17-alpine
    container_name: postgres-container
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pg_data_volume:/var/lib/postgresql/data
      - ./backup/postgres_dump-auth/dumps:/dumps
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always

  pg-import:
    build:
      context: .
      dockerfile: ./backup/postgres_dump-auth/Dockerfile
    environment:
      - PG_HOST=${POSTGRES_HOST}
      - PG_PORT=${POSTGRES_PORT}
      - PG_USER=${POSTGRES_USER}
      - PG_DB=${POSTGRES_DB}
      - PGPASSWORD=${POSTGRES_PASSWORD}
    depends_on:
      postgres:
        condition: service_healthy
      auth-api:
        condition: service_healthy

  nginx:
    image: nginx:1.27-alpine
    env_file: .env
    volumes:
      - ./infra/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./infra/nginx/configs:/etc/nginx/conf.d:ro
      - static_django:/var/www
    depends_on:
      - async-api
      - auth-api
    ports:
      - "${NGINX_PORT}:${NGINX_PORT}"
    restart: always

volumes:
  redis_data:
  pg_data_volume:
  elasticsearch_data:
  static_django:
