[tool.poetry]
name = "monorepo-tools"
version = "0.1.0"
description = "Common development tools"

[tool.poetry.dependencies]
python = "^3.12"

[tool.poetry.group.dev.dependencies]
pre-commit = "^4.1.0"
isort = "^6.0.0"
black = "^25.1.0"
pytest = "^8.3.4"
flake8 = "^7.1.2"
debugpy = "^1.8.13"
mypy = "^1.10.0"
ipython = "^9.1.0"

[build-system]
requires = ["poetry-core>=2.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 100
target-version = ['py312']
include = '\.pyi?$'
exclude = '''
/(
    \.git
    | \.venv
    | build
    | dist
    | migrations
)/
'''

[tool.isort]
profile = "black"
line_length = 100

[tool.flake8]
max-line-length = 100
exclude = [".git", "__pycache__", "venv", ".venv"]

[tool.pytest.ini_options]
asyncio_mode = "auto"
addopts = "--asyncio-mode=auto -W ignore::DeprecationWarning"
