
services:
  event-generator:
    build:
      # context: .
      context: ../..
      # dockerfile: ./src/Dockerfile
      dockerfile: services/event-generator/src/Dockerfile
    env_file:
      - ../../.env
    ports:
      - 8099:8000
    cpus: "1"
    mem_limit: 256M
    restart: always
