services:

  event-generator:
    container_name: generator
    build:
      context: ../..
      dockerfile: services/event-generator/src/Dockerfile
    image: event-generator:latest
    env_file:
      - ../../.env
    expose:
      - 8000:8000
    cpus: "1"
    mem_limit: 256M
    depends_on:
      rabbit-init:
        condition: service_completed_successfully

    restart: always


  celery-beat:
    container_name: celery-beat
    image: event-generator:latest   # <— и здесь тоже
    command: ["./scripts/run_celery.sh", "celery_beat"]
    working_dir: /opt/app          # на всякий случай
    env_file:
      - ../../.env
    restart: always

volumes:
  rabbitmq_data:
