include:
  - ../../infra/rabbit/docker-compose.rabbit.yml
services:

  event-generator:
    build:
      context: ../..
      dockerfile: services/event-generator/src/Dockerfile
    image: event-generator:latest
    env_file:
      - ../../.env
    ports:
      - 8077:8000
    cpus: "1"
    mem_limit: 256M
    depends_on:
      rabbitmq-1:
        condition: service_healthy
      rabbitmq-2:
        condition: service_healthy
      rabbitmq-3:
        condition: service_healthy

    restart: always


  celery-beat:
    image: event-generator:latest   # <— и здесь тоже
    command: ["./scripts/run_celery.sh", "celery_beat"]
    working_dir: /opt/app          # на всякий случай
    env_file:
      - ../../.env
    restart: always

volumes:
  rabbitmq_data:
