"""create template table

Revision ID: 554b65e7c8a4
Revises: 1991c0a7fe0b
Create Date: 2025-07-12 13:05:19.957097

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "554b65e7c8a4"
down_revision: Union[str, None] = "1991c0a7fe0b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "template",
        sa.Column("id", sa.Uuid(), nullable=False, comment="Уникальный идентификатор шаблона"),
        sa.Column("name", sa.String(length=100), nullable=False, comment="Наименование шаблона"),
        sa.Column("description", sa.String(length=500), nullable=False, comment="Описание шаблона"),
        sa.Column("template_type", sa.String(length=100), nullable=False, comment="Тип шаблона"),
        sa.Column("content", sa.Text(), nullable=False, comment="HTML код шаблона"),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        schema="email_sender",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("template", schema="email_sender")
    # ### end Alembic commands ###
