"""create template table

Revision ID: 9fc81b41456c
Revises: 1991c0a7fe0b
Create Date: 2025-07-06 17:07:49.085768

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9fc81b41456c"
down_revision: Union[str, None] = "1991c0a7fe0b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "template",
        sa.Column("id", sa.Uuid(), nullable=False, comment="Уникальный идентификатор шаблона"),
        sa.Column("content", sa.Text(), nullable=False, comment="HTML код шаблона"),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        schema="email_sender",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("template", schema="email_sender")
    # ### end Alembic commands ###
