"""create nlp table

Revision ID: 98059c9a3836
Revises: 05b618bcca23
Create Date: 2025-07-22 20:22:01.445712+00:00

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "98059c9a3836"
down_revision: Union[str, None] = "05b618bcca23"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "processed_npl",
        sa.Column(
            "id",
            sa.Uuid(),
            nullable=False,
            comment="Уникальный идентификатор уведомления",
        ),
        sa.Column(
            "user_id",
            sa.Uuid(),
            nullable=False,
            comment="ID пользователя, которому предназначено уведомление",
        ),
        sa.Column(
            "query",
            sa.String(length=1000),
            nullable=False,
            comment="Текст пользовательского запроса рекомендации",
        ),
        sa.Column(
            "processing_result",
            sa.String(length=100),
            nullable=False,
            comment="Результат обработки",
        ),
        sa.Column(
            "llm_resp",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            comment="Ответ LLM",
        ),
        sa.Column(
            "final_embedding",
            sa.ARRAY(sa.Float()),
            nullable=True,
            comment="Эмбеддинг, полученный в результате обработки запроса",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="nlp",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("processed_npl", schema="nlp")
    # ### end Alembic commands ###
