"""add uses field

Revision ID: 08af4348970d
Revises: 78b529914f60
Create Date: 2025-07-11 18:10:05.948202+00:00

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "08af4348970d"
down_revision: Union[str, None] = "78b529914f60"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "short_link",
        sa.Column(
            "uses_count",
            sa.BigInteger(),
            nullable=False,
            comment="Количество использований ссылки",
        ),
        schema="link",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("short_link", "uses_count", schema="link")
    # ### end Alembic commands ###
