"""add path field

Revision ID: 1c445c578e72
Revises: 380fa7b109f0
Create Date: 2025-07-11 18:54:04.666489+00:00

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1c445c578e72"
down_revision: Union[str, None] = "380fa7b109f0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "short_link",
        sa.Column(
            "short_path",
            sa.String(length=50),
            nullable=False,
            comment="Префикс для короткой ссылки",
        ),
        schema="link",
    )
    op.create_index(
        op.f("ix_link_short_link_short_path"),
        "short_link",
        ["short_path"],
        unique=True,
        schema="link",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_link_short_link_short_path"),
        table_name="short_link",
        schema="link",
    )
    op.drop_column("short_link", "short_path", schema="link")
    # ### end Alembic commands ###
