"""create link table

Revision ID: 78b529914f60
Revises: 1098f0631711
Create Date: 2025-07-11 17:54:14.950937+00:00

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "78b529914f60"
down_revision: Union[str, None] = "1098f0631711"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "short_link",
        sa.Column(
            "id",
            sa.Uuid(),
            nullable=False,
            comment="Уникальный идентификатор экземпляра короткой ссылки",
        ),
        sa.Column(
            "original_url",
            sa.String(length=3000),
            nullable=False,
            comment="Оригинальная ссылка",
        ),
        sa.Column(
            "short_url",
            sa.String(length=3000),
            nullable=False,
            comment="Сокращённая ссылка",
        ),
        sa.Column(
            "valid_to",
            sa.TIMESTAMP(timezone=True),
            nullable=False,
            comment="Дата до которой валидна короткая ссылка",
        ),
        sa.Column(
            "is_archive",
            sa.Boolean(),
            nullable=False,
            comment="Флаг архивности короткой ссылки",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="link",
    )
    op.create_index(
        op.f("ix_link_short_link_short_url"),
        "short_link",
        ["short_url"],
        unique=False,
        schema="link",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_link_short_link_short_url"),
        table_name="short_link",
        schema="link",
    )
    op.drop_table("short_link", schema="link")
    # ### end Alembic commands ###
