"""create recs table

Revision ID: 99d4ec14e77b
Revises: 2a04401f9855
Create Date: 2025-07-28 19:32:29.225086+00:00

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "99d4ec14e77b"
down_revision: Union[str, None] = "2a04401f9855"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_recs",
        sa.Column(
            "id",
            sa.Uuid(),
            nullable=False,
            comment="Уникальный идентификатор рекомендации.",
        ),
        sa.Column(
            "user_id",
            sa.Uuid(),
            nullable=False,
            comment="ID пользователя, для которого сохранена рекомендация.",
        ),
        sa.Column(
            "film_id",
            sa.Uuid(),
            nullable=False,
            comment="Идентификатор фильма, по которому была сохранена рекомендация.",
        ),
        sa.Column(
            "rec_source_type",
            sa.String(length=100),
            nullable=False,
            comment="Событие, вызвавшее создание рекомендации.",
        ),
        sa.Column(
            "embedding",
            sa.ARRAY(sa.Float()),
            nullable=True,
            comment="Эмбеддинг, полученный в результате обработки запроса.",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="recs_profile",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user_recs", schema="recs_profile")
    # ### end Alembic commands ###
