"""add index to recs table

Revision ID: 93cfb6512416
Revises: 99d4ec14e77b
Create Date: 2025-07-29 15:53:31.104830+00:00

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "93cfb6512416"
down_revision: Union[str, None] = "99d4ec14e77b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("ix_recs_profile_user_recs_user_id"),
        "user_recs",
        ["user_id"],
        unique=False,
        schema="recs_profile",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_recs_profile_user_recs_user_id"),
        table_name="user_recs",
        schema="recs_profile",
    )
    # ### end Alembic commands ###
